tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      export glbviewadd="https://8001-${GITPOD_WORKSPACE_URL}" && python3 -m pip install paho-mqtt && cd Docker && docker-compose up

