#
#       AUTHOR - Raman Sailopal
#
version: "2"
services:
 yottamgweb:
   hostname: yottamgweb
   image: ramb0/yotta-mgweb:latest 
   networks:
      - yottanet
   ports:
      - 8080:8080
      - 8001:8001
      - 7042:7042
   mem_limit: 1G
   volumes:
      - ../mapped:/opt/mgweb/mapped
      - ../entrypoint:/home/entrypoint
   environment:
      - glbviewport=8001
      - glbviewadd=$glbviewadd
      - ydb_gbldir=/opt/yottadb/yottadb.gld
   entrypoint: /home/entrypoint/entrypoint.sh

 mqtt:
   image: docker.io/toke/mosquitto
   ports:
      - 1883:1883
      - 9001:9001
   networks:
      - yottanet

 grafana:
   image: docker.io/grafana/grafana:latest
   volumes:
      - "$PWD/provisioning:/etc/grafana/provisioning"
   ports: 
      - 3001:3000
   networks:
      - yottanet
   environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource

 sensors:
   image: docker.io/ramb0/yottadb-python-client:latest
   networks:
      - yottanet
   volumes:
      - ..:/usr/local/YottaDB-IoT
      - ../sensor-entrypoint:/home/entrypoint
   environment:
      - NOPI=$NOPI
   entrypoint: /home/entrypoint/entrypoint.sh


networks:
    yottanet:

